name: Factions
version: 1.1-RELEASE
author: DoctorDark, joeleoli
main: me.joeleoli.hcfactions.FactionsPlugin
depend: [zPermissions]
softdepend: [ProtocolLib]
commands:
  ores:
  focus:
    aliases: [target]
  hcf:
  spawn:
  enderdragon:
  hub:
  this:
  playtime:
  cobble:
  crowgive:
     aliases: [crowbar, crowbargive]
  friend:
  hcfhelp:
      aliases: [help, ehelp]
  conquest:
    description: Command used to handle Conquest events.
  economy:
    aliases: [$, bal, balance, money, eco, econ]
    description: Command used to modify the economy.
  eotw:
    aliases: [endoftheworld]
    description: Sets if the server is in End of the World mode.
  event:
    description: Command used to manage event events.
  faction:
    aliases: [f, fac]
    description: Faction related commands.
  gopple:
    description: Command to check remaining OP apple cooldown time.
    aliases: [opple, goppletimer, goppletime, oppletimer, oppletime]
  hcf:
    aliases: [hardcorefactions, hcfactions]
  koth:
    description: Make or delete KotH arenas.
  lives:
    description: Management of lives or deathbans.
  location:
    aliases: [loc]
    description: Check the faction location of a player.
  logout:
    aliases: [disconnect]
    description: Command to safely logout without an NPC spawning.
  mapkit:
    aliases: [viewkit]
    description: Used to check the current map restrictions.
  pay:
    aliases: [p2p]
    description: Allow players to pay money.
  pvptimer:
    aliases: [pvp]
    description: Command to enable or disable pvp timer protection.
  regen:
    description: Check ETA until a faction is able to regenerate DTR.
  servertime:
    description: Checks the date and time of server.
  sotw:
    aliases: [startoftheworld]
    description: Command used to manage start of the world.
  spawncannon:
    aliases: [cannon, playercannon]
    description: Shoots you into the warzone.
  staffrevive:
    description: Command used by staff to revive players.
  timer:
    description: Command to manage timers.
  savedata:
    description: Save all player data (joeleoli).
  deathinfo:
  spawntoken:
    aliases: [spawntokens]
  claim:
    aliases: [reclaim]